// Login
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const GET_USER_AUTH_FIREBASE = 'GET_USER_AUTH_FIREBASE';
export const ADD_USER_FIREBASE = 'ADD_USER_FIREBASE';
export const SIGN_OUT = 'SIGN_OUT';

//Error
export const ERROR_HANDLING = 'ERROR_HANDLING';

//Map
export const SEARCH_LOCATION = 'SEARCH_LOCATION';
export const CURR_LOCATION = 'CURR_LOCATION';


